DEFAULT_STREAM_OUTPUT_PORT = 12500
DEFAULT_QUEUE_LENGTH = 100
DEFAULT_BROKER_REST_PORT = 10002
DEFAULT_EPICS_WRITER_URL = "http://localhost:10200/notify"
DEFAULT_LOG_LEVEL = "INFO"

DEFAULT_SEND_TIMEOUT = 1000
DEFAULT_RECEIVE_TIMEOUT = 1000
DEFAULT_DATA_RETRIEVAL_DELAY = 0

AUDIT_FILE_TIME_FORMAT = "%Y%m%d-%H%M%S"

DEFAULT_AUDIT_FILENAME = "/var/log/sf_databuffer_audit.log"

DATA_API_QUERY_ADDRESS = "https://data-api.psi.ch/sf/query"
DATA_BACKEND = "sf-databuffer"
IMAGE_BACKEND = "sf-imagebuffer"

BROKER_CHANNELS_LIMIT = 100
BROKER_CHANNELS_LIMIT_PICTURE = 2

ERROR_IF_NO_DATA = True
TRANSFORM_PULSE_ID_TO_TIMESTAMP_QUERY = False 
SEPARATE_CAMERA_CHANNELS = True
